from src.routers.auth import router as auth_router
from src.routers.health import router as health_router
from src.routers.logs import router as logs_router
from src.routers.threat_intel import router as threat_intel_router
from src.routers.ai import router as ai_router
from src.routers.case_management import router as case_management_router
from src.routers.dashboard import router as dashboard_router
from src.routers.detection import router as detection_router
from src.routers.enterprise import router as enterprise_router
from src.routers.plugins import router as plugins_router
